export enum ACTIVITY_TYPE {
  BUILDER_TOPUP = 'BUILDER_TOPUP',
  BUILDER_REGISTRATION = 'BUILDER_REGISTRATION',
  PROPOSER_REGISTRATION = 'PROPOSER_REGISTRATION',
  REPORTER_REGISTRATION = 'REPORTER_REGISTRATION'
}
